// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function About() {
  return window['go']['main']['App']['About']();
}

export function ClearImportedData() {
  return window['go']['main']['App']['ClearImportedData']();
}

export function Consolidate() {
  return window['go']['main']['App']['Consolidate']();
}

export function Export() {
  return window['go']['main']['App']['Export']();
}

export function ImportSource(arg1) {
  return window['go']['main']['App']['ImportSource'](arg1);
}

export function ImportState(arg1) {
  return window['go']['main']['App']['ImportState'](arg1);
}

export function InitialState() {
  return window['go']['main']['App']['InitialState']();
}

export function OpenSourceFromDialog() {
  return window['go']['main']['App']['OpenSourceFromDialog']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReviewLog(arg1, arg2) {
  return window['go']['main']['App']['ReviewLog'](arg1, arg2);
}

export function ReviewSource(arg1) {
  return window['go']['main']['App']['ReviewSource'](arg1);
}

export function ShowAbout() {
  return window['go']['main']['App']['ShowAbout']();
}
