// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function About():Promise<Record<string, string>>;

export function BackupDatabase():Promise<main.BackupResult>;

export function ClearImportedData():Promise<main.ClearResult>;

export function ConfigurationDocument():Promise<Array<main.SettingsTab>>;

export function Consolidate():Promise<main.ConsolidateResult>;

export function Export(arg1:string,arg2:string):Promise<main.ExportResult>;

export function ExportReviewData(arg1:string,arg2:string):Promise<main.ExportResult>;

export function ImportSource(arg1:string,arg2:string):Promise<main.ImportResult>;

export function ImportState(arg1:string):Promise<main.ImportState>;

export function InitialState():Promise<main.State>;

export function OpenConfigDirectory():Promise<void>;

export function OpenDataDirectory():Promise<void>;

export function OpenExportDirectory():Promise<void>;

export function Quit():Promise<void>;

export function ReviewLog(arg1:string,arg2:string,arg3:number,arg4:number):Promise<main.ReviewResult>;

export function ReviewSource(arg1:string,arg2:number,arg3:number):Promise<main.ReviewResult>;

export function SaveConfigurationFile(arg1:string,arg2:string):Promise<main.SettingsSaveResult>;

export function SelectExportTarget():Promise<main.ExportTarget>;

export function SelectImportFile(arg1:string):Promise<string>;

export function SelectReviewExportTarget(arg1:string):Promise<main.ExportTarget>;

export function ShowAbout():Promise<void>;

export function ShowSettings():Promise<void>;
