// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function About():Promise<Record<string, string>>;

export function ClearImportedData():Promise<main.ClearResult>;

export function Consolidate():Promise<main.ConsolidateResult>;

export function Export():Promise<main.ExportResult>;

export function ImportSource(arg1:string):Promise<main.ImportResult>;

export function ImportState(arg1:string):Promise<main.ImportState>;

export function InitialState():Promise<main.State>;

export function OpenSourceFromDialog():Promise<void>;

export function Quit():Promise<void>;

export function ReviewLog(arg1:string,arg2:string):Promise<main.ReviewResult>;

export function ReviewSource(arg1:string):Promise<main.ReviewResult>;

export function ShowAbout():Promise<void>;
