// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function About() {
  return window['go']['main']['App']['About']();
}

export function BackupDatabase() {
  return window['go']['main']['App']['BackupDatabase']();
}

export function ClearImportedData() {
  return window['go']['main']['App']['ClearImportedData']();
}

export function ConfigurationDocument() {
  return window['go']['main']['App']['ConfigurationDocument']();
}

export function Consolidate() {
  return window['go']['main']['App']['Consolidate']();
}

export function Export(arg1, arg2) {
  return window['go']['main']['App']['Export'](arg1, arg2);
}

export function ExportReviewData(arg1, arg2) {
  return window['go']['main']['App']['ExportReviewData'](arg1, arg2);
}

export function ImportSource(arg1, arg2) {
  return window['go']['main']['App']['ImportSource'](arg1, arg2);
}

export function ImportState(arg1) {
  return window['go']['main']['App']['ImportState'](arg1);
}

export function InitialState() {
  return window['go']['main']['App']['InitialState']();
}

export function OpenConfigDirectory() {
  return window['go']['main']['App']['OpenConfigDirectory']();
}

export function OpenDataDirectory() {
  return window['go']['main']['App']['OpenDataDirectory']();
}

export function OpenExportDirectory() {
  return window['go']['main']['App']['OpenExportDirectory']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReviewLog(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReviewLog'](arg1, arg2, arg3, arg4);
}

export function ReviewSource(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReviewSource'](arg1, arg2, arg3);
}

export function SaveConfigurationFile(arg1, arg2) {
  return window['go']['main']['App']['SaveConfigurationFile'](arg1, arg2);
}

export function SelectExportTarget() {
  return window['go']['main']['App']['SelectExportTarget']();
}

export function SelectImportFile(arg1) {
  return window['go']['main']['App']['SelectImportFile'](arg1);
}

export function SelectReviewExportTarget(arg1) {
  return window['go']['main']['App']['SelectReviewExportTarget'](arg1);
}

export function ShowAbout() {
  return window['go']['main']['App']['ShowAbout']();
}

export function ShowSettings() {
  return window['go']['main']['App']['ShowSettings']();
}
